# Generated by Django 4.2 on 2023-04-15 17:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Название заказа')),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы навыков')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('name', models.CharField(default='Test name', max_length=255, verbose_name='Название теста')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('third_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('photo', models.ImageField(upload_to='media/img/usersPhotos')),
                ('password', models.CharField(default='12345678', max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(default='defaultemail@mail.ru', max_length=254)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(default=datetime.datetime(2023, 4, 15, 22, 46, 5, 519325))),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(blank=True)),
                ('experience', models.IntegerField()),
                ('career_status', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workers_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.order')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Вопрос не задан')),
                ('variants', models.TextField(default='Вариант ответа')),
                ('correct_index', models.IntegerField(default=0)),
                ('correct', models.TextField(default='Правильный вариант ответа')),
                ('score', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.order')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skills_group'),
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.orderer'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
    ]
