# Generated by Django 4.2 on 2023-04-15 09:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Название заказа')),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('third_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('photo', models.ImageField(upload_to='media/img/usersPhotos')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(blank=True)),
                ('experience', models.IntegerField()),
                ('career_status', models.BooleanField(default=True)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workers_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.order')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.order')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.orderer'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user')),
            ],
        ),
    ]
