# Generated by Django 4.2 on 2023-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderer_id',
            new_name='orderer',
        ),
        migrations.RenameField(
            model_name='skills_orders',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='skills_orders',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.RenameField(
            model_name='worker_skills',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='worker_skills',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.RenameField(
            model_name='worker_tests',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='worker_tests',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.RenameField(
            model_name='workers_orders',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='workers_orders',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
