# Generated by Django 4.2 on 2023-04-15 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 19, 18, 10, 809289)),
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Вопрос не задан')),
                ('variants', models.TextField(default='Вариант ответа')),
                ('correct', models.TextField(default='Правильный вариант ответа')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
            ],
        ),
    ]
