# Generated by Django 4.2 on 2023-04-16 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_question',
            name='local_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 5, 56, 17, 705159)),
        ),
    ]
