# Generated by Django 4.2 on 2023-04-15 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0002_alter_order_orderer_alter_user_last_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 3, 24, 13, 759948)),
        ),
    ]
