# Generated by Django 4.2 on 2023-04-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0002_alter_user_last_login_date_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_question',
            name='correct_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 19, 22, 53, 635515)),
        ),
    ]
