# Generated by Django 4.2 on 2023-04-15 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0003_test_question_correct_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_question',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 19, 24, 44, 656584)),
        ),
    ]
