# Generated by Django 4.2 on 2023-04-15 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlivaJob', '0004_test_question_score_alter_user_last_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Test name', max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 19, 43, 19, 443179)),
        ),
        migrations.CreateModel(
            name='Test_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.skill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SlivaJob.test')),
            ],
        ),
    ]
